[package]
name = "metro2"
version = "0.1.0"
edition = "2018"
description = "Metro2 spec validator for the CDIA guide"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
